### ISSUE TITLE
20.2 Main Issue Tracker

### ISSUE THREAD

**Issue by rah1993** [infiniteflight/infiniteflight-docs#177]
20.2 Issues (Open or Closed) that require guide updates:

- [x] https://github.com/flyingdevelopmentstudio/infiniteflight-issues/issues/810
- [x] https://github.com/flyingdevelopmentstudio/infiniteflight-issues/issues/809
- [x] https://github.com/flyingdevelopmentstudio/infiniteflight-issues/issues/808
- [x] https://github.com/flyingdevelopmentstudio/infiniteflight-issues/issues/1084
