### ISSUE TITLE
Scenery Editor Guide Tracking

### ISSUE THREAD

**Issue by rah1993** [infiniteflight/infiniteflight-docs#349]
**Location:**

New Guide

**Action Required:**

- [x] Build KSAN and try not to mess it up
- [x] Organise Figma (see #351)
- [x] Create a brief contents list to work from
- [x] @carmichaelalonso to add restricted access to ensure only those in Alpha can access it (this includes for staging)
- [x] `/guide` style to be adjusted to account for new Scenery Editor Guide

**Sections Completed:**

- [x] User Interface
- [x] Getting Started
- [x] Buildings and Facades
- [x] Objects
